version: '3.8'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Reemplaza '124' con el GID de tu sistema si es diferente
        - DOCKER_GID=124 
    container_name: jenkins
    privileged: true
    ports:
      - "5050:8080"
      - "50050:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      # Monta la carpeta de configuración completa
      - ./casc_configs:/var/jenkins_home/casc_configs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net
    environment:
      # Apunta a la carpeta, Jenkins buscará los .yaml adentro
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

volumes:
  jenkins-data:

networks:
  jenkins-net: