version: '3.8'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_GID=124
    container_name: jenkins
    privileged: true
    ports:
      - "5050:8080"
      - "50050:50000"
    volumes:
      # Persistir datos de Jenkins
      - jenkins-data:/var/jenkins_home
      # Montamos el archivo de configuración, esto es más flexible que usar COPY
      - ./jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net

    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs/jenkins.yaml
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

volumes:
  jenkins-data:

networks:
  jenkins-net: