FROM jenkins/inbound-agent:alpine-jdk17

ARG TERRAFORM_VERSION=1.9.0
USER root

# Instala herramientas: python, pip, git, y las necesarias para instalar Terraform
RUN apk add --no-cache \
    python3 \
    py3-pip \
    git \
    curl \
    unzip

# Instala Terraform manualmente
RUN curl -LO "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" && \
    unzip "terraform_${TERRAFORM_VERSION}_linux_amd64.zip" && \
    mv terraform /usr/local/bin/ && \
    rm "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"

# Instala librerías de Python
RUN pip3 install --no-cache-dir --break-system-packages checkov moto

USER jenkins